import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


import Nav from './components/Nav'
import Hero from './components/Hero'
import  CorpOutsource  from './components/CorpOutsource'
import  Pros  from './components/Pros'
import  Tarifs  from './components/Tarifs'
import  Breakfasts  from './components/Breakfasts'
import  Lunches  from './components/Lunches'
import  Dinners  from './components/Dinners'
import  Drinks  from './components/Drinks'
import  BreakTime  from './components/BreakTime'
import  Trusted  from './components/Trusted'
import  Delivery  from './components/Delivery'
import  Clients  from './components/Clients'
import  Footer  from './components/Footer'
import  Reviews  from './components/Reviews'
import ReqModal from './components/ReqModal'
import { useSelector } from 'react-redux'



export default function Home() {

  const isShown = useSelector((state) => state.auth.reqModal)
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Корпоративное питание "ТутЕда"</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
        <link href="https://fonts.googleapis.com/css2?family=Bad+Script&amp;family=Montserrat:wght@400;600&amp;display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"></link>
      </Head>

      <Nav />
      <ReqModal show={ isShown }/>
      <Hero />
      <CorpOutsource />
      <Pros />
      <Tarifs />
      <Breakfasts />
      <Lunches />
      <Dinners />
      <Drinks />
      <BreakTime />
      <Trusted />
      <Delivery />
      <Clients />
      <Reviews />
      <Footer />
      
      
        
        {/* <CorpOutsource /> */}
        {/* <Tarifs /> */}
      {/* <Hero /> */}
      {/* <CorpOutsource />
      <Pros />
      <Tarifs />
      <Breakfasts />
      <Lunches />
      <Dinners />
      <Drinks />
      <BreakTime />  */}
    </div>
  )
}
